site_name: ALCF User Guide
nav:
  - Home: README.md
  - Polaris:
    - Getting Started: polaris/getting-started.md
    - Known Issues: polaris/known-issues.md
    - Hardware Overview:
      - Polaris Machine Overview: polaris/hardware-overview/machine-overview.md
      - Slingshot Network: polaris/hardware-overview/slingshot-network.md
    - Compiling and Linking:
      - Compiling and Linking Overview: polaris/compiling-and-linking/compiling-and-linking-overview.md
      - Programming Models: polaris/compiling-and-linking/polaris-programming-models.md
      - Example Program and Makefile: polaris/compiling-and-linking/polaris-example-program-makefile.md
      - CCE Compilers: polaris/compiling-and-linking/cce-compilers-polaris.md
      - GNU Compilers: polaris/compiling-and-linking/gnu-compilers-polaris.md
      - NVIDIA Compilers: polaris/compiling-and-linking/nvidia-compiler-polaris.md
      - LLVM Compilers: polaris/compiling-and-linking/llvm-compilers-polaris.md
      - Continuous Integration: polaris/compiling-and-linking/continuous-integration-polaris.md
    - Queueing and Running Jobs on Polaris:
      - Job Scheduling and Execution: polaris/queueing-and-running-jobs/job-and-queue-scheduling.md
      - Example Job Scripts: polaris/queueing-and-running-jobs/example-job-scripts.md
      - Cobalt to PBS option Comparison: polaris/queueing-and-running-jobs/pbs-qsub-options-table.md
      - The Grounkulator (Job Status Display): polaris/queueing-and-running-jobs/gronkulator.md
      - PBS Admin Quick Start Guide: polaris/queueing-and-running-jobs/pbs-admin-quick-start-guide.md
    - Data Management:
        - ALCF Community Data Co-Op: polaris/data-management/acdc/acdc-overview.md
        - Sharing on Eagle: polaris/data-management/acdc/eagle-data-sharing.md
        - Data Transfer:
          - SFTP and SCP: polaris/data-management/data-transfer/sftp-scp.md
          - Using Globus: polaris/data-management/data-transfer/using-globus.md
        - File System & Storage:
          - Polaris Disk Quota: polaris/data-management/filesystem-and-storage/polaris-disk-quota.md
    - Applications and Libraries:
        - Applications:
            - LAMMPS: polaris/applications-and-libraries/applications/lammps.md
        - Libraries:
            - Math Libraries: polaris/applications-and-libraries/libraries/math-libraries.md
    - Data Science Workflows:
        - Containers: polaris/data-science-workflows/containers/containers.md
        - Balsam: polaris/data-science-workflows/balsam.md
    - Programming Models: 
        - OpenMP: polaris/programming-models/openmp-polaris.md
        - SYCL: polaris/programming-models/sycl-polaris.md
    - Debugging Tools:
        - Debugging Tools Overview: polaris/debugging-tools/debugging-overview.md
        - CUDA-GDB: polaris/debugging-tools/CUDA-GDB.md
    - Performance Tools:
        - Performance Tools Overview: polaris/performance-tools/performance-overview.md
        - NVIDIA-Nsight: polaris/performance-tools/NVIDIA-Nsight.md
  - Theta:
    - Hardware Overview:
      - Theta Machine Overview: theta/hardware-overview/machine-overview.md
      - Theta Memory Modes: theta/hardware-overview/theta-memory-modes.md
      - Aries Network: theta/hardware-overview/aries-network.md
    - Compiling And Linking:
      - Compiling and Linking Overview: theta/compiling-and-linking/compiling-and-linking-overview.md
      - Library and Compiler Tracking: theta/compiling-and-linking/theta-library-compiler-tracking-overview.md
      - Example Program and Makefile: theta/compiling-and-linking/theta-example-program-makefile.md
      - Clang Compiler: theta/compiling-and-linking/clang-compiler-theta.md
      - Continuous Integration: theta/compiling-and-linking/continuous-integration-theta.md
    - Queueing and Running Jobs on Theta:
      - The Grounkulator (Job Status Display): theta/queueing-and-running-jobs/gronkulator.md
      - Job and Queue Scheduling: theta/queueing-and-running-jobs/job-and-queue-scheduling.md
      - Machine Reservations: theta/queueing-and-running-jobs/machine-reservations.md
      - Affinity on Theta: theta/queueing-and-running-jobs/affinity-theta.md
    - Data Management:
        - ALCF Community Data Co-Op: theta/data-management/acdc/acdc-overview.md
        - Sharing on Eagle Using Globus: theta/data-management/acdc/eagle-data-sharing.md
        - Data Transfer:
          - SFTP and SCP: theta/data-management/data-transfer/sftp-scp.md
          - Using Globus: theta/data-management/data-transfer/using-globus.md
        - File System & Storage:
          - Theta File Systems: theta/data-management/filesystem-and-storage/theta-file-systems.md
          - HPSS: theta/data-management/filesystem-and-storage/hpss.md
          - Theta Disk Quota: theta/data-management/filesystem-and-storage/theta-disk-quota.md
    - Applications and Libraries:
        - Applications:
          - ELPA: theta/applications-and-libraries/applications/elpa.md
          - Grommacs: theta/applications-and-libraries/applications/grommacs.md
          - LAMMPS: theta/applications-and-libraries/applications/lammps.md
          - NAMD: theta/applications-and-libraries/applications/namd.md
          - NwChem: theta/applications-and-libraries/applications/nwchem.md
          - QMCPack: theta/applications-and-libraries/applications/qmcpack.md
          - Quantum Espresso: theta/applications-and-libraries/applications/quantum-espresso.md
          - Quantum Package: theta/applications-and-libraries/applications/quantum-package.md
          - VASP: theta/applications-and-libraries/applications/vasp.md
          - WEST: theta/applications-and-libraries/applications/west.md
    - Data Science Workflows:
          - Balsam: theta/data-science-workflows/balsam.md
    - Programming Models: 
          - OpenMP: theta/programming-models/openmp-theta.md
    - Debugging Tools: theta/debugging-tools/debugging-overview.md
    - Performance Tools: theta/performance-tools/performance-overview.md 
  - ThetaGPU:
      - System Overview and Node Information: theta-gpu/system-overview-and-node-information.md
      - GPU Node Queues and Policy: theta-gpu/gpu-node-queue-and-policy.md
      - GPU Monitoring: theta-gpu/gpu-monitoring.md
      - Python Virtual Environments: theta-gpu/python-venvs.md
      - MPI:
          - MPI: theta-gpu/mpi.md
          - DaskMPI: theta-gpu/daskmpi/README.md
      - Singularity Containers: theta-gpu/singularity-containers.md
      - Building Python Packages in a Container: theta-gpu/building-python-packages.md
      - Jupyter: theta-gpu/jupyter.md
      - DL Frameworks:
        - TensorFlow:
          - Running with Singularity: theta-gpu/ml-frameworks/tensorflow/nvidia-container-notes.md
          - Running with Conda: theta-gpu/ml-frameworks/tensorflow/running-with-conda.md
          - Tensorboard: theta-gpu/ml-frameworks/tensorflow/tensorboard-instructions.md
        - PyTorch:
          - Running with Conda: theta-gpu/ml-frameworks/pytorch/running-with-conda.md
        - Data Parallel Training: theta-gpu/data-parallel-training.md
      - Building and Compiling:
        - Python/C++ code interoperability: theta-gpu/building-and-compiling/README.md
        - Compiling and Linking: theta-gpu/building-and-compiling/compiling_and_linking.md
      - Balsam: theta-gpu/balsam.md
      - DeepHyper: theta-gpu/deephyper.md
  - Cooley:
      - System Overview and Node Information: cooley/system-overview-and-node-information.md
  - Edith (Edge Dev Testbed):
      - Getting Started: polaris/queueing-and-running-jobs/edtb.md

theme:
  name: 'material'
  custom_dir: overrides
  language: 'en'
  palette:
    scheme: alcf
  font:
    text: proxima-nova
  features:
    - tabs
    - instant
    - search.highlight
    - search.suggest
  logo: 'images/Argonne_wireframe_white_transparent.png'
  favicon: 'images/alcf_favicon.ico'

extra_css:
  - stylesheets/alcf-extra.css

extra_javascript:
  - javascripts/alcf-extra.js

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

repo_name: 'argonne-lcf/alcf-userguide'
repo_url: 'https://github.com/argonne-lcf/alcf-userguide'

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/argonne-lcf/alcf-userguide'

plugins:
  - search



